# Generated by Django 5.2.7 on 2025-10-22 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro', models.CharField(max_length=30, unique=True)),
                ('fecha', models.DateField()),
                ('vencimiento', models.DateField()),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('PARCIAL', 'Parcial'), ('PAGADA', 'Pagada'), ('ANULADA', 'Anulada')], default='ABIERTA', max_length=20)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('moneda', models.CharField(default='ARS', max_length=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='FacturaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('impuesto', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='facturacion.factura')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('medio', models.CharField(blank=True, max_length=30, null=True)),
                ('referencia', models.CharField(blank=True, max_length=60, null=True)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facturacion.factura')),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('estado', models.CharField(choices=[('EN_EVALUACION', 'En evaluación'), ('EN_CURSO', 'En curso'), ('EN_PAUSA', 'En pausa'), ('CERRADO_G', 'Cerrado (g)'), ('CERRADO_P', 'Cerrado (p)')], default='EN_EVALUACION', max_length=20)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin_prev', models.DateField(blank=True, null=True)),
                ('margen_objetivo', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente')),
            ],
        ),
        migrations.AddField(
            model_name='factura',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facturacion.proyecto'),
        ),
    ]
