# Generated by Django 5.2.7 on 2025-10-27 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_historialcliente'),
        ('facturacion', '0002_alter_pago_factura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='margen_objetivo',
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(choices=[('EN_PROCESO', 'EN_PROCESO'), ('PAUSADO', 'PAUSADO'), ('FINALIZADO', 'FINALIZADO')], default='EN_PROCESO', max_length=20),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
    ]
