# Generated by Django 5.2.7 on 2025-10-27 20:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0003_remove_proyecto_margen_objetivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaitem',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='facturaitem',
            name='descripcion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='facturaitem',
            name='precio_unit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='facturaitem',
            name='qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
