# Generated by Django 5.2.7 on 2025-10-27 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0004_facturaitem_descuento_alter_facturaitem_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturaitem',
            name='descuento',
        ),
    ]
