# Generated by Django 5.2.7 on 2025-11-04 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0006_alter_factura_options_alter_factura_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturaitem',
            name='impuesto',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True),
        ),
    ]
